### ISSUE TITLE
Update to version 1.31.6

### ISSUE THREAD

**Issue by tomgeor** [hroncok/slic3r-prusa3d#1]
Is there any interest in updating the RPM in your copr repo to version 1.31.6?  I've been testing the 1.31.4 on Fedora 24 and have been pleased with the improvements the Prusa team have made.
https://github.com/prusa3d/Slic3r/releases/tag/version_1.31.6

**Comment by hroncok** [comment]
Sure, will try tomorrow. I also have some little tweaks in mind.

**Comment by tomgeor** [comment]
I'm still interested in trying a newer version with your tweaks, if you still want to do it.

**Comment by hroncok** [comment]
Yes. Thanks for a reminder. Let's do it now...

**Comment by hroncok** [comment]
Trying to build just the updated version locally.

**Comment by hroncok** [comment]
TODO list:

* [X] Build new version locally
* [X] Bundle admesh
* [X] Recommend Thread::Queue for faster slicing
* [x] Unbundle glew if possible
* [ ] <del>Remove bundled Shiny profiler (not needed for users)</del> (not possible easily enough)
* [x] Try to install it ad run it (fix errors)
* [x] Build in Copr

**Comment by hroncok** [comment]
https://copr.fedorainfracloud.org/coprs/churchyard/slic3r-prusa3d/monitor/

**Comment by hroncok** [comment]
Could you give it a try?

**Comment by tomgeor** [comment]
Absolutely, I just installed in from your copr.  Thanks for building it, I'll start running some prints tomorrow.

**Comment by tomgeor** [comment]
So far I haven't run into any problems with it, I've tried a handful of STLs and have a 7 hr print running with one of models that took quite some time to slice.

**Comment by hroncok** [comment]
OK, closing it. Applied for package in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1405714
